# experiment
data_root: ../data/training_data/
training_name: resnet50
trainer: BatCLSTrainer

# training
n_epochs: 20
batch_size: 8
learning_rate: 1e-4
optimizer: Adam
base_lr: 0.00005
max_lr: 0.0005
step_size_up: 15
scheduler_mode: triangular
weight_decay: 0.0003

# loss
loss: CrossEntropyLoss

# architecture
model_name: resnet50
pretrained: True
num_classes: 96

# checkpoint
checkpoint_metric: acc
checkpoint_metric_goal: maximize

# dataset
input_size: [224, 224]
seed: 42
train_size: 0.7
val_size: 0.15
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# augmentations
rotation_degrees: 15
sharpness_factor: 2
brightness: 0.2
contrast: 0.2
saturation: 0.2
hue: 0.1